on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interaction
    steps:
      - name: test
        run:  devnet-mjex-xmph.snippets.sh deploy
